apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service-deployment
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        # image from gcr.io
        # replace on gcp
        image: api-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
