# Generated by Django 4.1.4 on 2022-12-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendors_contract_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendors',
            name='vendor_number',
            field=models.CharField(max_length=64),
        ),
    ]
